# Pre actions
before_script:
  - echo "Running tpt build"

# Delete artifacts after 5 days
default:
  artifacts:
    expire_in: 5 days

stages:          # List of stages for jobs, and their order of execution
  - do_nothing

do_nothing:
  stage: do_nothing
  tags:
    - axsim-runner
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_MERGE_REQUEST_ID'
  script:
    - echo "This does nothing right now"

after_script:
  - echo "Completed trick build"
